#Author: Ryan Burns

package:
    name: pyre
    version: 1.0

requirements:
    build:
        - git
    host:
        - python
    run:
        - python

about:
    home: http://pyre.orthologue.com
    summary: an application framework for scientific applications
    dev_url: https://github.com/pyre/pyre

source:
    - git_url: https://github.com/aivazis/config
      folder: config
    - git_url: https://github.com/pyre/pyre
      folder: pyre

test:
    imports:
        - pyre
        - journal
