{% set version = "2.3.1" %}

package:
    name: isce2
    version: {{ version }}

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - scons
        - cython
    host:
        - python
        - gdal
        - fftw
        - cython
    run:
        - python
        - gdal
        - libgdal
        - numpy
        - scipy
        - fftw
about:
    home: http://winsar.unavco.org/software/isce.html
    summary: insar scientific computing environment
    dev_url: https://github.com/isce-framework/isce2

source:
      url: https://github.com/isce-framework/isce2/archive/v{{ version }}.tar.gz
      folder: isce2
      sha256: 0ff07d8d86bab899b0855baabdb949eb7b0d5df8eef70a0a4c530c75ca033ad0

test:
    imports:
        - isce
